export const allCategories = {
    'Atacado': '01',
    'Casas de Carne Peixaria': '02',
    'Docerias Confeitarias Rotisserie': '03',
    'Feira livre': '04',
    'Hortifruit Granjeiros': '05',
    'Lojas de Conveniência': '06',
    'Mercearia e Bebidas': '07',
    'Alimentação em geral': '08',
    'Supermercado': '22',
    'Padaria': '23',
    'Restaurante': '27',
    'Restaurante Fast Food': '29',
    'Pizzaria': '99',
    'Lojas de Laticínios': '245',
    'Bijouterias': '09',
    'Calçados Bolsas Malas': '10',
    'Cosméticos Produtos de bele': '11',
    'Lavanderia Tinturaria': '12',
    'Magazines': '13',
    'Roupas masc.,fem.,inf.,geral': '14',
    'Uniformes': '15',
    'Vestuário': '25',
    'Joalheria': '32',
    'Material de Construção': '17',
    'Adm.de condomínios': '88',
    'Empreiteiros Arquitetos Engenheiros': '89',
    'Imobiliárias Construtoras Incorporadoras': '90',
    'Cama Mesa Banho': '95',
    'Chaveiros': '96',
    'Concessionárias(Gás,Energia,Água)': '97',
    'Móveis em geral': '98',
    'Tinta e Material de pintura': '100',
    'Moradia em geral': '101',
    'Lojas de Departamento': '102',
    'Lojas de Madeira e Material de Construção': '115',
    'Móveis e Artigos de Decoração': '203',
    'Computadores,Periféricos e Software': '18',
    'Papelaria,Material de Escritório': '19',
    'Banca de Jornal': '20',
    'Floricultura': '21',
    'Eletrônicos': '26',
    'Advogados Escritório advocacia': '67',
    'Artesanato': '68',
    'Associações religiosas': '69',
    'Associações políticas': '70',
    'Cartório': '71',
    'Casa lotérica': '72',
    'Cia seguro': '73',
    'Despachante': '74',
    'Escritório contabilidade': '75',
    'Feiras e eventos': '76',
    'Produtos importados': '77',
    'Provedor acesso internet': '78',
    'Recarga bilhete único Celular': '79',
    'Serviços públicos': '80',
    'TV por assinatura': '81',
    'Venda em domicílio': '82',
    'Profissionais Liberais': '103',
    'Desenvolvimento de software': '106',
    'Feiras e eventos': '107',
    'Pagamento de Impostos': '114',
    'Câmera e Fotografia ': '199',
    'Artigos de Costura': '200',
    'Lojas Variadas': '205',
    'Bens Não Duráveis': '206',
    'Presentes e Novidades': '207',
    'Lojas de Eletrodomésticos': '208',
    'Lojas de Bebidas': '211',
    'Lojas de Sapatos': '212',
    'Lojas de Conserto de Rádios': '213',
    'Equipamento Comercial': '214',
    'Software': '216',
    'Lojas de Móveis de Escritório': '218',
    'Lojas de Acessórios Variados': '221',
    'Cortinados,Vitrines e Estofados': '222',
    'Combustível': '223',
    'Bens Duráveis': '225',
    'Cooperativas de Agricultores': '226',
    'Lojas de Reparação e Pneus': '230',
    'Floriculturas': '231',
    'Lojas de Papelaria,Escritório e Suprimentos Escolares': '232',
    'Ônibus de Tour': '236',
    'Associações Sociais,Fraternas e Cívicas': '241',
    'Produtos Secos': '242',
    'Equipamentos,Ferramentas e Aluguel de Aparelhos': '243',
    'Lojas de Mercadorias Usadas': '244',
    'Equipamentos Elétricos': '246',
    'Pedras Preciosas,Metais,Relógios e Jóias': '247',
    'Centro de Serviços de Metais': '248',
    'Lojas de Aparelhos e Reparos Elétricos': '249',
    'Transporte': '251',
    'Cuidados Infantis': '252',
    'Instituições Finaceiras': '253',
    'Equipamentos e Suprimento de Aquecimento': '254',
    'Lojas de Reparo': '255',
    'Negociantes de Barco': '256',
    'Reparo de Móveis': '257',
    'Produção e Distribuição de Filmes': '259',
    'Lojas de Móveis Domésticos': '261',
    'Empreiteiros de Carpintaria': '263',
    'Fotografia': '266',
    'Produtos Químicos e Relacionados': '268',
    'Marketing': '269',
    'Alfaiates,Costureiras,Remendos e Alterações': '270',
    'Aluguel de Roupas': '276',
    'Lojas de Aluguel de Fitas de Vídeo': '277',
    'Lojas de Música': '280',
    'Posto de Combustível': '24',
    'Auto escola': '40',
    'Borracharia': '41',
    'Estacionamento': '42',
    'Lava rápido': '43',
    'Locadora de veículos': '44',
    'Pedágio': '45',
    'Táxi Cia de táxi': '46',
    'Veículos em geral': '47',
    'Lojas de Serviços Automotivos': '201',
    'Concessionárias de Motocicletas': '209',
    'Concessionárias de Carros Usados': '210',
    'Revenda Automotiva': '227',
    'Suprimentos para Veículos Motori': '234',
    'Lojas e Serviços de Bicicleta': '235',
    'Lojas de Reparo Automotivo': '238',
    'Bar e Casa Noturna': '28',
    'Cia marítima': '48',
    'Agências turismo': '49',
    'Casa de câmbio': '50',
    'Cia ferrovia': '51',
    'Cia terrestre': '52',
    'Cinema': '53',
    'Clube': '54',
    'Hotel Pousada Motel  Flat': '55',
    'Turismo em geral': '56',
    'Farmácia,Drogaria': '30',
    'Hospital Maternidade': '34',
    'Médico': '35',
    'Dentista': '36',
    'Óticas': '37',
    'Veterinário Clínica veterinária': '38',
    'Saúde em geral': '39',
    'Clínicas e Institutos especiali': '91',
    'Artigos para animais Petshop': '92',
    'Casa de asilo': '93',
    'Fono Nutricionista Físio  Psicólogo': '94',
    'Dispositivos Protéticos de Artigos Ortopédicos': '215',
    'Laboratórios Médicos e Odontológicos': '224',
    'Equipamentos Médicos,Hospitalares e Odontológicos': '229',
    'Osteopatas': '271',
    'Cateters': '272',
    'Livraria': '31',
    'Editora': '83',
    'Escola Cursos em geral': '84',
    'Escola Faculdade': '85',
    'Transporte escolar': '86',
    'Educação em geral': '87',
    'Escola de Negócios': '250',
    'Loja de Brinquedos': '33',
    'Academias em geral': '57',
    'Aluguel de quadras': '58',
    'Arte': '59',
    'Artigos música - Discos CD DVD': '60',
    'Artigos pesca Caça Camping': '61',
    'Personal Trainer': '62',
    'Pintura Desenho': '63',
    'Produtos Eróticos(SEX SHOP)': '64',
    'Salão de Bele': '65',
    'Tabacaria': '66',
    'Outras atividades auxiliares dos serviços financeiros não especificado anteriormente': '105',
    'Serviços de Publicidade': '202',
    'Serviços Funerários e Crematório': '204',
    'Empreiteira': '217',
    'Manutenção de Computadores': '219',
    'Serviços Pessoais Diversos': '220',
    'Gestão,Relações Públicas e Serviços de Consultoria': '233',
    'Contratantes de Comerciantes Especiais': '237',
    'Empreiteiros Elétricos': '240',
    'Serviços de Cópia Rápida e Reprodução': '260',
    'Oficinas de Conserto,Engraxate e Chapelaria': '262',
    'Composição,Fabricação de Chapas e Serviços Relacionados': '264',
    'Serviços de Reboque': '265',
    'Empreiteiros de Aquecimento - Vendas,Serviço,Instalação': '273',
    'Relógios e Conserto de Joias': '274',
    'Preparações Especiais de Limpeza,Polimento e Saneamento': '275',
    'Serviços de Paisagismo': '278',
    'Limpeza e Manutenção,Serviços de Zeladoria': '279',
    'Telhados - Empreiteiros': '281',
    'Estúdios Fotográficos': '228',
    'Videogame': '239',
    'Suprimentos Industriais': '258',
    'Atrações e Exposições Turísticas': '267'
};

export const categoryList = ['Atacado',
    'Casas de Carne Peixaria',
    'Docerias Confeitarias Rotisserie',
    'Feira livre',
    'Hortifruit Granjeiros',
    'Lojas de Conveniência',
    'Mercearia e Bebidas',
    'Alimentação em geral',
    'Supermercado',
    'Padaria',
    'Restaurante',
    'Restaurante Fast Food',
    'Pizzaria',
    'Lojas de Laticínios',
    'Bijouterias',
    'Calçados Bolsas Malas',
    'Cosméticos Produtos de bele',
    'Lavanderia Tinturaria',
    'Magazines',
    'Roupas masc.,fem.,inf.,geral',
    'Uniformes',
    'Vestuário',
    'Joalheria',
    'Material de Construção',
    'Adm.de condomínios',
    'Empreiteiros Arquitetos Engenheiros',
    'Imobiliárias Construtoras Incorporadoras',
    'Cama Mesa Banho',
    'Chaveiros',
    'Concessionárias(Gás,Energia,Água)',
    'Móveis em geral',
    'Tinta e Material de pintura',
    'Moradia em geral',
    'Lojas de Departamento',
    'Lojas de Madeira e Material de Construção',
    'Móveis e Artigos de Decoração',
    'Computadores,Periféricos e Software',
    'Papelaria,Material de Escritório',
    'Banca de Jornal',
    'Floricultura',
    'Eletrônicos',
    'Advogados Escritório advocacia',
    'Artesanato',
    'Associações religiosas',
    'Associações políticas',
    'Cartório',
    'Casa lotérica',
    'Cia seguro',
    'Despachante',
    'Escritório contabilidade',
    'Feiras e eventos',
    'Produtos importados',
    'Provedor acesso internet',
    'Recarga bilhete único Celular',
    'Serviços públicos',
    'TV por assinatura',
    'Venda em domicílio',
    'Profissionais Liberais',
    'Desenvolvimento de software',
    'Pagamento de Impostos',
    'Câmera e Fotografia ',
    'Artigos de Costura',
    'Lojas Variadas',
    'Bens Não Duráveis',
    'Presentes e Novidades',
    'Lojas de Eletrodomésticos',
    'Lojas de Bebidas',
    'Lojas de Sapatos',
    'Lojas de Conserto de Rádios',
    'Equipamento Comercial',
    'Software',
    'Lojas de Móveis de Escritório',
    'Lojas de Acessórios Variados',
    'Cortinados,Vitrines e Estofados',
    'Combustível',
    'Bens Duráveis',
    'Cooperativas de Agricultores',
    'Lojas de Reparação e Pneus',
    'Floriculturas',
    'Lojas de Papelaria,Escritório e Suprimentos Escolares',
    'Ônibus de Tour',
    'Associações Sociais,Fraternas e Cívicas',
    'Produtos Secos',
    'Equipamentos,Ferramentas e Aluguel de Aparelhos',
    'Lojas de Mercadorias Usadas',
    'Equipamentos Elétricos',
    'Pedras Preciosas,Metais,Relógios e Jóias',
    'Centro de Serviços de Metais',
    'Lojas de Aparelhos e Reparos Elétricos',
    'Transporte',
    'Cuidados Infantis',
    'Instituições Finaceiras',
    'Equipamentos e Suprimento de Aquecimento',
    'Lojas de Reparo',
    'Negociantes de Barco',
    'Reparo de Móveis',
    'Produção e Distribuição de Filmes',
    'Lojas de Móveis Domésticos',
    'Empreiteiros de Carpintaria',
    'Fotografia',
    'Produtos Químicos e Relacionados',
    'Marketing',
    'Alfaiates,Costureiras,Remendos e Alterações',
    'Aluguel de Roupas',
    'Lojas de Aluguel de Fitas de Vídeo',
    'Lojas de Música',
    'Posto de Combustível',
    'Auto escola',
    'Borracharia',
    'Estacionamento',
    'Lava rápido',
    'Locadora de veículos',
    'Pedágio',
    'Táxi Cia de táxi',
    'Veículos em geral',
    'Lojas de Serviços Automotivos',
    'Concessionárias de Motocicletas',
    'Concessionárias de Carros Usados',
    'Revenda Automotiva',
    'Suprimentos para Veículos Motori',
    'Lojas e Serviços de Bicicleta',
    'Lojas de Reparo Automotivo',
    'Bar e Casa Noturna',
    'Cia marítima',
    'Agências turismo',
    'Casa de câmbio',
    'Cia ferrovia',
    'Cia terrestre',
    'Cinema',
    'Clube',
    'Hotel Pousada Motel  Flat',
    'Turismo em geral',
    'Farmácia,Drogaria',
    'Hospital Maternidade',
    'Médico',
    'Dentista',
    'Óticas',
    'Veterinário Clínica veterinária',
    'Saúde em geral',
    'Clínicas e Institutos especiali',
    'Artigos para animais Petshop',
    'Casa de asilo',
    'Fono Nutricionista Físio  Psicólogo',
    'Dispositivos Protéticos de Artigos Ortopédicos',
    'Laboratórios Médicos e Odontológicos',
    'Equipamentos Médicos,Hospitalares e Odontológicos',
    'Osteopatas',
    'Cateters',
    'Livraria',
    'Editora',
    'Escola Cursos em geral',
    'Escola Faculdade',
    'Transporte escolar',
    'Educação em geral',
    'Escola de Negócios',
    'Loja de Brinquedos',
    'Academias em geral',
    'Aluguel de quadras',
    'Arte',
    'Artigos música - Discos CD DVD',
    'Artigos pesca Caça Camping',
    'Personal Trainer',
    'Pintura Desenho',
    'Produtos Eróticos(SEX SHOP)',
    'Salão de Bele',
    'Tabacaria',
    'Outras atividades auxiliares dos serviços financeiros não especificado anteriormente',
    'Serviços de Publicidade',
    'Serviços Funerários e Crematório',
    'Empreiteira',
    'Manutenção de Computadores',
    'Serviços Pessoais Diversos',
    'Gestão,Relações Públicas e Serviços de Consultoria',
    'Contratantes de Comerciantes Especiais',
    'Empreiteiros Elétricos',
    'Serviços de Cópia Rápida e Reprodução',
    'Oficinas de Conserto,Engraxate e Chapelaria',
    'Composição,Fabricação de Chapas e Serviços Relacionados',
    'Serviços de Reboque',
    'Empreiteiros de Aquecimento - Vendas,Serviço,Instalação',
    'Relógios e Conserto de Joias',
    'Preparações Especiais de Limpeza,Polimento e Saneamento',
    'Serviços de Paisagismo',
    'Limpeza e Manutenção,Serviços de Zeladoria',
    'Telhados - Empreiteiros',
    'Estúdios Fotográficos',
    'Videogame',
    'Suprimentos Industriais',
    'Atrações e Exposições Turísticas'];
