export const banksList = [
    "000 - Banco Bankpar S.A.",
    "001 - Banco do Brasil",
    "003 - Banco da Amazônia S.A.",
    "004 - Banco do Nordeste do Brasil S.",
    "012 - Banco Standard de Investimento",
    "014 - Natixis Brasil S.A. Banco Múlt",
    "018 - Banco Tricury S.A.",
    "019 - Banco Azteca do Brasil S.A.",
    "021 - BANESTES S.A. Banco do Estado ",
    "024 - Banco BANDEPE S.A.",
    "025 - Banco Alfa S.A.",
    "029 - Banco Banerj S.A.",
    "031 - Banco Beg S.A.",
    "033 - Banco S",
    "036 - Banco Bradesco BBI S.A.",
    "037 - Banco do Estado do Pará S.A.",
    "039 - Banco do Estado do Piauí S.A. ",
    "040 - Banco Cargill S.A.",
    "041 - Banco do Estado do Rio Grande ",
    "044 - Banco BVA S.A.",
    "045 - Banco Opportunity S.A.",
    "047 - Banco do Estado de Sergipe S.A",
    "062 - Hipercard Banco Múltiplo S.A.",
    "063 - Banco Ibi S.A. Banco Múltiplo",
    "064 - Goldman Sachs do Brasil Banco ",
    "065 - Banco Bracce S.A.",
    "066 - Banco Morgan Stanley S.A.",
    "069 - BPN Brasil Banco Múltiplo S.A.",
    "070 - BRB - Banco de Brasília S.A.",
    "072 - Banco Rural Mais S.A.",
    "073 - BB Banco Popular do Brasil S.A",
    "074 - Banco J. Safra S.A.",
    "075 - Banco ABN AMRO S.A.",
    "076 - Banco KDB S.A.",
    "077 - Banco Intermedium S.A.",
    "078 - BES Investimento do Brasil S.A",
    "079 - Banco Original do Agronegócio ",
    "081 - BBN Banco Brasileiro de Negóci",
    "082 - Banco Topázio S.A.",
    "083 - Banco da China Brasil S.A.",
    "084 - Unicred Norte do Paraná",
    "085 - Cooperativa Central de Crédito",
    "086 - OBOE Crédito Financiamento e I",
    "087 - Cooperativa Unicred Central Sa",
    "088 - Banco Randon S.A.",
    "089 - Cooperativa de Crédito Rural d",
    "090 - Cooperativa Central de Economi",
    "091 - Unicred Central do Rio Grande ",
    "092 - Brickell S.A. Crédito, financi",
    "093 - Pólocred SCM",
    "301 - BPP INSTITUIÇÃO DE PAGAMENTO",
    "094 - Banco Petra S.A.",
    "095 - Banco Confidence de Câmbio S.A",
    "096 - Banco BM&amp;FBOVESPA de Servi",
    "097 - Cooperativa Central de Crédito",
    "098 - CREDIALIANÇA COOPERATIVA DE CR",
    "099 - Cooperativa Central de Economi",
    "104 - Caixa Econô",
    "107 - Banco BBM S.A.",
    "114 - Central das Coop. de Economia ",
    "119 - Banco Western Union do Brasil ",
    "121 - Banco Gerador S.A",
    "121 - Banco Agibank S.A.",
    "122 - Banco BERJ S.A.",
    "125 - Brasil Plural S.A. - Banco Múl",
    "130 - Banco Caruana SCFI",
    "133 - Cresol Confederação",
    "136 - CONFEDERACAO NACIONAL DAS COOP",
    "168 - HSBC Finance(Brasil) S.A. - B",
    "172 - Albatross Corretora",
    "184 - Banco Itaú BBA S.A.",
    "197 - Stone Pagamentos S.A",
    "204 - Banco Bradesco Cartões S.A.",
    "208 - Banco BTG Pactual S.A.",
    "212 - Banco Original S.A.",
    "213 - Banco Arbi S.A.",
    "214 - Banco Dibens S.A.",
    "215 - Banco Comercial e de Investime",
    "217 - Banco John Deere S.A.",
    "218 - Banco Bonsucesso S.A.",
    "222 - Banco Credit Agricole Brasil S",
    "224 - Banco Fibra S.A.",
    "225 - Banco Brascan S.A.",
    "229 - Banco Cruzeiro do Sul S.A.",
    "230 - Unicard Banco Múltiplo S.A.",
    "233 - Banco Cifra S.A.",
    "237 - Banco Br",
    "237 - Banco Next",
    "241 - Banco Clássico S.A.",
    "243 - Banco Máxima S.A.",
    "246 - Banco ABC Brasil S.A.",
    "248 - Banco Boavista Interatlântico ",
    "249 - Banco Investcred Unibanco S.A.",
    "250 - BCV - Banco de Crédito e Varej",
    "254 - Paraná Banco S.A.",
    "260 - Nubank",
    "263 - Banco Cacique S.A.",
    "265 - Banco Fator S.A.",
    "266 - Banco Cédula S.A.",
    "273 - Sulcredi(Cooperativa de Credi",
    "290 - Pagseguro Internet S.A.",
    "300 - Banco de La Nacion Argentina",
    "318 - Banco BMG S.A.",
    "320 - Banco Industrial e Comercial S",
    "336 - C6",
    "341 - Itaú Unibanc",
    "336 - C6 Bank",
    "356 - Banco Real S.A.",
    "366 - Banco Société Générale Brasil ",
    "370 - Banco Mizuho do Brasil S.A.",
    "376 - Banco J.P.Morgan S.A.",
    "389 - Banco Mercantil do Brasil S.A.",
    "394 - Banco Bradesco Financiamentos ",
    "394 - Banco Finasa BMC S.A.",
    "399 - HSBC Bank Br",
    "409 - UNIBANCO - União de Bancos Bra",
    "412 - Banco Capital S.A.",
    "422 - Banco Safra",
    "453 - Banco Rural S.A.",
    "456 - Banco de Tokyo - Mitsubishi UFJ ",
    "464 - Banco Sumitomo Mitsui Brasilei",
    "473 - Banco Caixa Geral - Brasil S.A",
    "477 - Citibank",
    "479 - Banco ItaúBank S.A.",
    "487 - Deutsche Bank S.A. - Banco Ale",
    "488 - JPMorgan Chase Bank",
    "492 - ING Bank N.V.",
    "494 - Banco de La Republica Oriental",
    "495 - Banco de La Provincia de Bueno",
    "505 - Banco Credit Suisse(Brasil) S",
    "600 - Banco Luso Brasileiro S.A.",
    "604 - Banco Industrial do Brasil S.A",
    "610 - Banco VR S.A.",
    "611 - Banco Paulista S.A.",
    "612 - Banco Guanabara S.A.",
    "613 - Banco Pecúnia S.A.",
    "623 - Banco Panamericano S.A.",
    "626 - Banco Ficsa S.A.",
    "630 - Banco Intercap S.A.",
    "633 - Banco Rendimento S.A.",
    "634 - Banco Triângulo S.A.",
    "637 - Banco Sofisa S.A.",
    "638 - Banco Prosper S.A.",
    "641 - Banco Alvorada S.A.",
    "643 - Banco Pine S.A.",
    "652 - Itaú Unibanco Holding S.A.",
    "653 - Banco Indusval S.A.",
    "654 - Banco A.J.Renner S.A.",
    "655 - Banco Votorantim S.A.",
    "707 - Banco Daycoval S.A.",
    "712 - Banco Ourinvest S.A.",
    "719 - Banif - Banco Internacional do F",
    "721 - Banco Credibel S.A.",
    "724 - Banco Porto Seguro S.A.",
    "734 - Banco Gerdau S.A.",
    "735 - Banco Pottencial S.A.",
    "738 - Banco Morada S.A.",
    "739 - Banco Cetelem S.A.",
    "740 - Banco Barclays S.A.",
    "741 - Banco Ribeirão Preto S.A.",
    "743 - Banco Semear S.A.",
    "744 - BankBoston N.A.",
    "745 - Banco Citibank S.A.",
    "746 - Banco Modal S.A.",
    "747 - Banco Rabobank International B",
    "748 - Banco Cooperativo Sicredi S.A.",
    "749 - Banco Simples S.A.",
    "751 - Scotiabank Brasil S.A.Banco M",
    "752 - Banco BNP Paribas Brasil S.A.",
    "753 - NBC Bank Brasil S.A. - Banco M",
    "755 - Bank of America Merrill Lynch ",
    "756 - Banco Cooperativo do Brasil S.",
    "757 - Banco KEB do Brasil S.A.",
    "9991 - Conductor FlexAssists",
    "9992 - Conductor Alpha Card",
    "M03 - Banco Fiat S.A.",
    "M06 - Banco de Lage Landen Brasil S.",
    "M07 - Banco GMAC S.A.",
    "M08 - Banco Citicard S.A.",
    "M09 - Banco Itaucred Financiamentos ",
    "M10 - Banco Moneo S.A.",
    "M11 - Banco IBM S.A.",
    "M12 - Banco Maxinvest S.A.",
    "M14 - Banco Volkswagen S.A.",
    "M15 - Banco BRJ S.A.",
    "M16 - Banco Rodobens S.A.",
    "M18 - Banco Ford S.A.",
    "M19 - Banco CNH Industrial Capital S",
    "M20 - Banco Toyota do Brasil S.A.",
    "M21 - Banco Daimlerchrysler S.A.",
    "M22 - Banco Honda S.A.",
    "M23 - Banco Volvo(Brasil) S.A.",
    "M24 - Banco PSA Finance Brasil S.A."
]